#it is for mac, change some of the docker images if you want to use it for linux environment
#export $(cat .env) > /dev/null 2>&1; docker compose -f local-docker-compose-mac.yaml up -d
version: "3.9"
services:
  eiedp_web:
    image: debbyku/copo_new:v3.0.u2204
    command: >
      sleep infinity
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT_TYPE=local
      - ASPERA_PLUGIN_DIRECTORY=aspera_linux_plugin
      - SECRET_KEY=${vault_copo_web_secret_key}
      - MEDIA_PATH=media/
      - DEBUG=true
      - REDIS_HOST=eiedp_redis
      - REDIS_PORT=6379
      - WEBIN_USER=${vault_copo_webin_user}
      - WEBIN_USER_PASSWORD=${vault_copo_webin_user_password}
      - ENA_SERVICE=https://wwwdev.ebi.ac.uk/ena/submit/drop-box/submit/
      - MONGO_USER=eiedp_user
      - MONGO_USER_PASSWORD=password
      - MONGO_DB=eiedp_mongo
      - MONGO_HOST=eiedp_mongo
      - MONGO_PORT=27017
      - MONGO_MAX_POOL_SIZE=100
      - POSTGRES_DB=eiedp
      - POSTGRES_USER=eiedp_user
      - POSTGRES_PORT=5432
      - POSTGRES_SERVICE=eiedp_postgres
      - POSTGRES_PASSWORD=password
      - ORCID_SECRET=${vault_copo_orcid_secret_key}
      - ORCID_CLIENT=${vault_copo_orcid_client_id}
      - NIH_API_KEY=${vault_copo_nih_api_key}
      - PUBLIC_NAME_SERVICE_API_KEY=${vault_copo_public_name_service_api_key}
      - MAIL_PASSWORD=${vault_copo_mail_password}
      - MAIL_PORT=587
      - MAIL_ADDRESS=data@earlham.ac.uk
      - MAIL_SERVER=outlook.office365.com
      - MAIL_USERNAME=eidata@nbi.ac.uk
      - ALLOWED_HOSTS=
      - PUBLIC_NAME_SERVICE=https://id.tol.sanger.ac.uk/api/v2/
      - ENA_ENDPOINT_REPORT=https://wwwdev.ebi.ac.uk/ena/submit/report/
      - ASPERA_PATH=/root/.aspera/cli
      - BIOIMAGE_PATH=${vault_copo_bioimage_path}
      - BIOIMAGE_SERVER=bsaspera_w@hx-fasp-1.ebi.ac.uk
      - ECS_SECRET_KEY=${vault_ecs_secret_key}
      - ECS_ACCESS_KEY_ID=copo@nbi.ac.uk
      - ECS_ENDPOINT=https://ei-copo.obj-data.nbi.ac.uk
      - ENA_V2_SERVICE_SYNC=https://wwwdev.ebi.ac.uk/ena/submit/webin-v2/submit
      - ENA_V2_SERVICE_ASYNC=https://wwwdev.ebi.ac.uk/ena/submit/webin-v2/submit/queue
      - ENA_V1_SAMPLE_SERVICE=https://wwwdev.ebi.ac.uk/ena/submit/drop-box/samples
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@test.com
    depends_on:
      - eiedp_redis
      - eiedp_postgres
      - eiedp_mongo
    volumes:
      - /Users/zef22hak/development/ei-edp:/copo
    restart: always
  eiedp_redis:
    image: redis:6.2.8
    restart: always
  eiedp_postgres:
    image: postgres:15
    ports:
      - "5442:5432"  
    environment:
      - POSTGRES_DB=eiedp
      - POSTGRES_USER=eiedp_user
      - POSTGRES_PASSWORD=password
    restart: always
  eiedp_mongo:
    image: copo/copo-mongo-mac:v7.0.1
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/replica.key
    entrypoint:
       - bash
       - -c
       - |
          openssl rand -base64 756 > /data/replica.key
          chmod 400 /data/replica.key
          chown 999:999 /data/replica.key
          exec docker-entrypoint.sh $$@
    hostname: eiedp-mongo-server
    ports:
      - "27027:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eiedp_admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_USER=eiedp_user
      - MONGO_USER_PASSWORD=password
      - MONGO_DB=eiedp_mongo
    restart: always
