version: "3.9"
services:
  new_web:
    image: debbyku/copo_new:v2.0.u2204
    command: >
      sleep infinity
      #bash -c "code-server serve-local --disable-telemetry --auth none --host 0.0.0.0 --port 8101"
    ports:
      - "8000:8000"
      - "8101:8101"
    volumes:
      - /Users/zef22hak/development/COPO_refactoring/COPO-production:/copo
    environment:
      - ENVIRONMENT_TYPE=local
      - ASPERA_PLUGIN_DIRECTORY=aspera_linux_plugin
      - SECRET_KEY_FILE=/run/secrets/copo_web_secret_key
      - MEDIA_PATH=media/
      - DEBUG=true
      - REDIS_HOST=copo_redis
      - REDIS_PORT=6379
      - WEBIN_USER_FILE=/run/secrets/copo_webin_user
      - WEBIN_USER_PASSWORD_FILE=/run/secrets/copo_webin_user_password
      - ENA_SERVICE=https://wwwdev.ebi.ac.uk/ena/submit/drop-box/submit/
      - ENA_V2_SERVICE_SYNC=https://wwwdev.ebi.ac.uk/ena/submit/webin-v2/submit
      - ENA_V2_SERVICE_ASYNC=https://wwwdev.ebi.ac.uk/ena/submit/webin-v2/submit/queue
      - MONGO_USER=copo_user
      - MONGO_USER_PASSWORD_FILE=/run/secrets/copo_mongo_user_password
      - MONGO_DB=copo_mongo
      - MONGO_HOST=copo_mongo
      - MONGO_PORT=27017
      - MONGO_MAX_POOL_SIZE=100
      - POSTGRES_DB=copo
      - POSTGRES_USER=copo_user
      - POSTGRES_PORT=5432
      - POSTGRES_SERVICE=copo_postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/copo_postgres_user_password
      - ORCID_SECRET_FILE=/run/secrets/copo_orcid_secret_key
      - ORCID_CLIENT_FILE=/run/secrets/copo_orcid_client_id
      - NIH_API_KEY_FILE=/run/secrets/copo_nih_api_key
      - PUBLIC_NAME_SERVICE_API_KEY_FILE=/run/secrets/copo_public_name_service_api_key
      - MAIL_PASSWORD_FILE=/run/secrets/copo_mail_password
      - MAIL_PORT=587
      - MAIL_ADDRESS=data@earlham.ac.uk
      - MAIL_SERVER=outlook.office365.com
      - MAIL_USERNAME=eidata@nbi.ac.uk
      - ALLOWED_HOSTS=
      - PUBLIC_NAME_SERVICE=https://id.tol.sanger.ac.uk/api/v2/
      - ENA_ENDPOINT_REPORT=https://wwwdev.ebi.ac.uk/ena/submit/report/
      - ASPERA_PATH=/root/.aspera/cli
      - BIOIMAGE_PATH_FILE=/run/secrets/copo_bioimage_path
      - BIOIMAGE_SERVER=bsaspera_w@hx-fasp-1.ebi.ac.uk
      - ECS_SECRET_KEY_FILE=/run/secrets/ecs_secret_key
      - ECS_ACCESS_KEY_ID=copo@nbi.ac.uk
      - ECS_ENDPOINT=http://ei-copo.obj-data.nbi.ac.uk
      - SELENIUM_TEST_USERNAME=debby.ku@earlham.ac.uk
      - SELENIUM_TEST_PASSWORD=Iam1testUser
    depends_on:
      - redis
      - postgres
      - mongo
    networks:
      default:
        aliases:
          - copo-new.cyverseuk.org
      copo-backend-network:
    deploy:
      replicas : 1
      #endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.web-service==true"
      resources:
        limits:
          cpus: "4"
          memory: 12GB
        reservations:
          cpus: "1"
          memory: 1GB
      update_config:
        parallelism: 1
        delay: 10s
    secrets:
      - copo_web_secret_key
      - copo_postgres_user_password
      - copo_mongo_user_password
      - copo_orcid_secret_key
      - copo_orcid_client_id
      - copo_webin_user
      - copo_webin_user_password
      - copo_nih_api_key
      - copo_public_name_service_api_key
      - copo_mail_password
      - copo_bioimage_path
      - ecs_secret_key
  redis:
    image: redis:6.2.8
    networks:
      - copo-backend-network
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.web-service==true"
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: 1GB
        reservations:
          cpus: "0.3"
          memory: 512mb

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"    
    networks:
      - copo-backend-network
    volumes:
      - postgres-data1:/var/lib/postgresql/data
    secrets:
      - copo_postgres_user_password
    environment:
      - POSTGRES_DB=copo
      - POSTGRES_USER=copo_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/copo_postgres_user_password
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS="--data-checksums"
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.postgres-service==true"
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: 1GB
        reservations:
          cpus: "0.3"
          memory: 512mb

  mongo:
    image: debbyku/mongodb:v7.0.1_1
    command: mongod --replSet rs0 --bind_ip_all --keyFile /data/replica.key
    entrypoint:
       - bash
       - -c
       - |
          openssl rand -base64 756 > /data/replica.key
          chmod 400 /data/replica.key
          chown 999:999 /data/replica.key
          exec docker-entrypoint.sh $$@    
    hostname: copo-mongo-server    
    networks:
      - copo-backend-network
    volumes:
      - mongo-data2:/data/db
    secrets:
      - copo_mongo_initdb_root_password
      - copo_mongo_user_password
    ports:
      - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=copo_admin
     - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/copo_mongo_initdb_root_password
     - MONGO_USER=copo_user
     - MONGO_USER_PASSWORD_FILE=/run/secrets/copo_mongo_user_password
     - MONGO_DB=copo_mongo 
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.mongo-service==true"
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "2"
          memory: 3GB
        reservations:
          cpus: "0.4"
          memory: 512mb
  browser:
    image: debbyku/browserless.chrome
    networks:
      - default
      - copo-backend-network
    ports:
     - "3000:3000"
    environment:
      - COPO_WEB_USER=debby.ku@earlham.ac.uk
      - COPO_WEB_USER_PW=Iam1testUser
      - COPO_WEB_URL=http://copo-new.cyverseuk.org:8000
      - BROWSERLESS_HTTP_URL=http://copo_browser:3000
      - BROWSERLESS_WS_URL=ws://copo_browser:3000
      - KEEP_ALIVE=true
      - PREBOOT_CHROME=true
      - MAX_CONCURRENT_SESSIONS=5
      - MAX_QUEUE_LENGTH=10
      - PREBOOT_QUANTITY=2
      - CHROME_REFRESH_TIME=1800000
      - BROWSERLESS_TRACKING_ID=UA-123456789-1
      - CHROME_REFRESH_TIME_RANDOMNESS=10000
      - CHROME_ARGS=--no-sandbox,--keepalive=30000,--disable-dev-shm-usage,--disable-gpu,--disable-setuid-sandbox,--disable-software-rasterizer,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu-sandbox,--disable-infobars,--disable-notifications,--disable-extensions,--disable-web-security,--disable-features=IsolateOrigins,site-per-process,--disable-site-isolat
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.web-service==true"
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "1"
          memory: 1GB
        reservations:
          cpus: "0.4"
          memory: 512mb
  edp:
    image: python:3.10.13-bullseye
    command: sleep infinity
    networks: 
      - copo-backend-network
      - common-network
    volumes:
      - /Users/zef22hak/development/EDP:/EDP
    environment:
      - SAPIOURL=https://earlham-test.exemplarlims.com/webservice/api
      - SAPIOGUID=08118b8d-4f43-4c09-9c87-7342cb7ce5ed
      - SAPIOTOKEN=377gywjzhgr10lgvp5tysvhmxutt9ke821eqgixyrpkxp2zo2j
      - ZENODOURL=https://zenodo.org/api
      - ZENODOTOKEN=EiSk26ncbosa3yHyxLk6qAbu8kkoeRdIpPEDr4rdfxIBjxej61irXDzQN29e
    deploy:
      replicas: 1
      #endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.labels.backup-service==true"
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "1"
          memory: 1GB
        reservations:
          cpus: "0.4"
          memory: 512mb
networks:
  copo-backend-network:
    external: true
  copo-frontend-network:
    external: true
  common-network:
    external: true
secrets:
  copo_web_secret_key:
    external: true
  copo_postgres_user_password:
    external: true
  copo_mongo_user_password:
    external: true
  copo_orcid_secret_key:
    external: true
  copo_orcid_client_id:
    external: true
  copo_webin_user:
    external: true
  copo_webin_user_password:
    external: true
  copo_nih_api_key:
    external: true
  copo_public_name_service_api_key:
    external: true
  copo_mail_password:
    external: true
  copo_postgres_user_password:
    external: true
  copo_mongo_initdb_root_password:
    external: true
  copo_mongo_user_password:
    external: true
  copo-project.crt:
    external: true
  copo-project.key:
    external: true
  copo_bioimage_path:
    external: true  
  ecs_secret_key:
    external: true
volumes:
  web-data:
    external: true
  static-data:
    external: true
  submission-data:
    external: true
  logs-data:
    external: true
  mongo-backup:
    external: true
  postgres-backup:
    external: true
  mongo-data2:
    external: true
  postgres-data1:
    external: true

